#!/bin/bash

set -eu

################################################################################
# FUNCTIONS
################################################################################

  Show_Help()
  {
    echo && cat ./docs/help/stack.txt && echo
  }

  Docker_Container_Is_Running()
  {
    sudo docker container ls -a | grep -q "${container_name}" -

    return $?
  }

  Start_Mitm_Proxy()
  {
    ############################################################################
    # INPUT
    ############################################################################

      local background_mode="${1? Missing background mode !!!}"

      local wifi_ip_address="${2? Missing Wifi Ip Address !!!}"


    ############################################################################
    # VARS
    ############################################################################

      local count=3

      local container_name="${PWD##*/}_proxy"


    ############################################################################
    # EXECUTION
    ############################################################################

      printf "\n---> PROXY SERVER: ${wifi_ip_address}\n"

      sudo docker run \
        --rm \
        ${background_mode} \
        --name "${container_name}" \
        --net host \
        --volume ~/.mitmproxy:/home/mitmproxy/.mitmproxy \
        mitmproxy/mitmproxy:4.0.4 mitmweb \
          --listen-host "${wifi_ip_address}" \
          --listen-port 8080 \
          --web-iface "${wifi_ip_address}" \
          --verbose

      printf "Booting"

      while [ ${count} -ge 1 ]; do
        printf "."
        sleep 1
        local count=$(( count - 1 ))
      done

      printf "\n"

      if ! Docker_Container_Is_Running "${container_name}"; then
        printf "\nAlready running a Proxy server on the Wifi Ip Address: ${wifi_ip_address}  !!!\n\n"
        exit 1
      fi
  }

  Stop_Docker_Container()
  {
    ############################################################################
    # INPUT
    ############################################################################

      local docker_stack_name="${1? Missing docker stack name!!!}"


    ############################################################################
    # VARS
    ############################################################################

      local container_name="${PWD##*/}_${docker_stack_name}"


    ##########################################################################
    # EXECUTION
    ##########################################################################

      if Docker_Container_Is_Running "${container_name}"; then
        sudo docker container stop "${container_name}"
      fi
  }

################################################################################
# MAIN
################################################################################

  Main()
  {
    ############################################################################
    # VARS
    ############################################################################

      local background_mode="-it"


    ############################################################################
    # INPUT
    ############################################################################

      for input in "${@}"; do
        case "${input}" in

          -d | --detach )
            local background_mode="--detach"
            shift 1
            ;;

          -h | --help )
            Show_Help
            exit $?
            ;;

          -it )
            local background_mode="-it"
            shift 1
          ;;

          down )
            shift 1

            case "${@}" in

              proxy )
                Stop_Docker_Container "proxy"
              ;;

              * )
                Stop_Docker_Container "proxy"
              ;;

            esac

            exit $?
          ;;

          up )
            shift 1

            case "${1:-}" in

              proxy )
                shift 1
                Start_Mitm_Proxy "${background_mode}" ${@}
                exit $?
              ;;

              * )
                Show_Help
                exit $?
              ;;
            esac

          ;;
        esac
      done

      Show_Help
}

Main "${@}"
